import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { DoorsQuantityProvider } from "./hooks/doorsQuantityContext";
import { CorrectDoorProvider } from "./hooks/correctDoorContext";
import { SelectedDoorProvider } from "./hooks/selectedDoorContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<DoorsQuantityProvider>
			<CorrectDoorProvider>
				<SelectedDoorProvider>
					<html lang="en">
						<body className={inter.className}>{children}</body>
					</html>
				</SelectedDoorProvider>
			</CorrectDoorProvider>
		</DoorsQuantityProvider>
	);
}
